name: test_web_three
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=2.19.1 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.3.6
  logger: ^1.4.0
  eartho_one: ^1.2.3
  jwt_decoder: ^2.0.1

  push_api_dart:
    path: ../push-api-dart
  ethers: ^0.0.1+3
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
